language: elixir
notifications:
  recipients:
    - klaus.alfert@googlemail.com
otp_release:
  - 18.2.1
elixir_
  - 1.2.2
before_script:
  - mix local.hex --force
  - mix local.rebar
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
